config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/1.7.4
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/I2PC/scipion-docker:
      branch: afteribergrid
      repo: https://github.com/I2PC/scipion-docker
    github.com/scipion-em/docs:
      branch: release-3.0.0
      repo: https://github.com/scipion-em/docs
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/I2PC/scipion-docker git:
        commands:
        - /usr/bin/env sh .sqa/script.freaky-turquoise-caterpillar.sh
        container: qc.acc_shabby-champagne-toucan
  QC.Doc:
    repos:
      github.com/scipion-em/docs find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.gimpy-lilac-bee.sh
        container: qc.doc_chewy-vermilion-impala
      github.com/scipion-em/docs git:
        commands:
        - /usr/bin/env sh .sqa/script.baggy-lavender-macaque.sh
        container: qc.doc_wimpy-tan-gecko
      github.com/scipion-em/docs restructuredtext-lint:
        commands:
        - /usr/bin/env sh .sqa/script.muzzy-viridian-turtle.sh
        container: qc.doc_zippy-harlequin-tamarin
  QC.Lic:
    repos:
      github.com/I2PC/scipion-docker licensee:
        commands:
        - /usr/bin/env sh .sqa/script.thirsty-goldenrod-coati.sh
        container: qc.lic_shaggy-cinnabar-squirrel
  QC.Sty:
    repos:
      github.com/I2PC/scipion-docker hadolint:
        commands:
        - /usr/bin/env sh .sqa/script.breezy-celadon-dodo.sh
        container: qc.sty_cozy-teal-mule
  QC.Ver:
    repos:
      github.com/I2PC/scipion-docker get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.flimsy-razzmatazz-stoat.sh
        container: qc.ver_shaggy-bistre-rhinoceros
timeout: 1800
