config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/1.7.2
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/I2PC/scipion-docker:
      branch: master
      repo: https://github.com/I2PC/scipion-docker
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/I2PC/scipion-docker git:
        commands:
        - /usr/bin/env sh .sqa/script.skinny-malachite-seal.sh
        container: qc.acc_boozy-amethyst-mammoth
  QC.Doc:
    repos:
      github.com/I2PC/scipion-docker find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.goopy-viridian-fish.sh
        container: qc.doc_pretty-black-booby
      github.com/I2PC/scipion-docker git:
        commands:
        - /usr/bin/env sh .sqa/script.dorky-cobalt-capuchin.sh
        container: qc.doc_stinky-violet-hummingbird
      github.com/I2PC/scipion-docker markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.wimpy-maroon-tarantula.sh
        container: qc.doc_squeaky-azure-shrew
  QC.Lic:
    repos:
      github.com/I2PC/scipion-docker licensee:
        commands:
        - /usr/bin/env sh .sqa/script.cloudy-taupe-barb.sh
        container: qc.lic_baggy-buff-numbat
  QC.Sec:
    repos:
      github.com/I2PC/scipion-docker bandit:
        commands:
        - /usr/bin/env sh .sqa/script.stinky-chocolate-grouse.sh
        container: qc.sec_flabby-purple-sloth
  QC.Sty:
    repos:
      github.com/I2PC/scipion-docker flake8:
        commands:
        - /usr/bin/env sh .sqa/script.lousy-jade-duck.sh
        container: qc.sty_bumpy-champagne-chipmunk
      github.com/I2PC/scipion-docker hadolint:
        commands:
        - /usr/bin/env sh .sqa/script.pokey-linen-chihuahua.sh
        container: qc.sty_paltry-azure-pinscher
      github.com/I2PC/scipion-docker jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.snappy-black-catfish.sh
        container: qc.sty_muggy-aqua-tarsier
  QC.Ver:
    repos:
      github.com/I2PC/scipion-docker get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.dorky-sapphire-urchin.sh
        container: qc.ver_stealthy-lime-tarantula
timeout: 1800
