config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/1.7.4
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/I2PC/scipion-docker:
      branch: ibergrid22
      repo: https://github.com/I2PC/scipion-docker
    github.com/Ratolon/docs:
      branch: ibergrid22
      repo: https://github.com/Ratolon/docs
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/I2PC/scipion-docker git:
        commands:
        - /usr/bin/env sh .sqa/script.whiny-ultramarine-millipede.sh
        container: qc.acc_homey-cobalt-stoat
  QC.Doc:
    repos:
      github.com/Ratolon/docs find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.shaky-emerald-spaniel.sh
        container: qc.doc_muzzy-pumpkin-turtle
      github.com/Ratolon/docs git:
        commands:
        - /usr/bin/env sh .sqa/script.tasty-periwinkle-caterpillar.sh
        container: qc.doc_stuffy-cerise-kiwi
      github.com/Ratolon/docs markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.snippy-ruby-otter.sh
        container: qc.doc_cloudy-alizarin-dhole
      github.com/Ratolon/docs restructuredtext-lint:
        commands:
        - /usr/bin/env sh .sqa/script.trippy-grey-dane.sh
        container: qc.doc_nippy-khaki-tiger
  QC.Lic:
    repos:
      github.com/I2PC/scipion-docker licensee:
        commands:
        - /usr/bin/env sh .sqa/script.leaky-puce-dog.sh
        container: qc.lic_ugly-indigo-havanese
  QC.Sty:
    repos:
      github.com/I2PC/scipion-docker hadolint:
        commands:
        - /usr/bin/env sh .sqa/script.cozy-razzmatazz-lemur.sh
        container: qc.sty_skanky-maroon-worm
  QC.Ver:
    repos:
      github.com/I2PC/scipion-docker get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.paltry-mauve-lemming.sh
        container: qc.ver_grumpy-malachite-loon
timeout: 1800
