config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/1.7.4
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/Ratolon/docs:
      branch: ibergrid22
      repo: https://github.com/Ratolon/docs
    github.com/Ratolon/scipion-docker:
      branch: ibergrid22
      repo: https://github.com/Ratolon/scipion-docker
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/Ratolon/scipion-docker git:
        commands:
        - /usr/bin/env sh .sqa/script.smelly-crimson-hedgehog.sh
        container: qc.acc_surly-coral-orangutan
  QC.Doc:
    repos:
      github.com/Ratolon/docs find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.chummy-mauve-ferret.sh
        container: qc.doc_nerdy-ruby-fox
      github.com/Ratolon/docs git:
        commands:
        - /usr/bin/env sh .sqa/script.slimy-grey-magpie.sh
        container: qc.doc_seedy-xanthic-uguisu
      github.com/Ratolon/docs markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.chummy-pumpkin-liger.sh
        container: qc.doc_whiny-myrtle-chin
      github.com/Ratolon/docs restructuredtext-lint:
        commands:
        - /usr/bin/env sh .sqa/script.homey-peach-hare.sh
        container: qc.doc_zippy-puce-bordeaux
  QC.Lic:
    repos:
      github.com/Ratolon/scipion-docker licensee:
        commands:
        - /usr/bin/env sh .sqa/script.lumpy-brown-dugong.sh
        container: qc.lic_freaky-pink-hamster
  QC.Sty:
    repos:
      github.com/Ratolon/scipion-docker hadolint:
        commands:
        - /usr/bin/env sh .sqa/script.flimsy-buff-dhole.sh
        container: qc.sty_homely-brown-mayfly
  QC.Ver:
    repos:
      github.com/Ratolon/scipion-docker get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.droopy-platinum-barracuda.sh
        container: qc.ver_pasty-cream-macaw
timeout: 1800
