config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/scipion-docker:
      branch: master
      repo: https://github.com/EOSC-synergy/scipion-docker
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/1.7.5
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/EOSC-synergy/scipion-docker git:
        commands:
        - /usr/bin/env sh .sqa/script.scaly-chartreuse-forest.sh
        container: qc.acc_freaky-linen-monkey
  QC.Doc:
    repos:
      github.com/EOSC-synergy/scipion-docker find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.snippy-cream-albatross.sh
        container: qc.doc_gamy-blue-gar
      github.com/EOSC-synergy/scipion-docker git:
        commands:
        - /usr/bin/env sh .sqa/script.scummy-red-mammoth.sh
        container: qc.doc_geeky-corn-olm
      github.com/EOSC-synergy/scipion-docker markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.whiny-yellow-hamster.sh
        container: qc.doc_sunny-beige-whale
  QC.Lic:
    repos:
      github.com/EOSC-synergy/scipion-docker licensee:
        commands:
        - /usr/bin/env sh .sqa/script.sunny-cerise-hyena.sh
        container: qc.lic_lumpy-pumpkin-ostrich
  QC.Sty:
    repos:
      github.com/EOSC-synergy/scipion-docker hadolint:
        commands:
        - /usr/bin/env sh .sqa/script.sleazy-firebrick-sparrow.sh
        container: qc.sty_pokey-razzmatazz-mandrill
  QC.Ver:
    repos:
      github.com/EOSC-synergy/scipion-docker get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.slimy-cream-bobcat.sh
        container: qc.ver_tacky-rose-owl
timeout: 1800
