config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/1.7.4
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/Ratolon/scipion-docker:
      branch: ibergrid22
      repo: https://github.com/Ratolon/scipion-docker
    github.com/scipion-em/docs:
      branch: release-3.0.0
      repo: https://github.com/scipion-em/docs
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/Ratolon/scipion-docker git:
        commands:
        - /usr/bin/env sh .sqa/script.fuzzy-violet-termite.sh
        container: qc.acc_snappy-platinum-paradise
  QC.Doc:
    repos:
      github.com/scipion-em/docs find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.cranky-amaranth-dragon.sh
        container: qc.doc_skimpy-cyan-chow
      github.com/scipion-em/docs git:
        commands:
        - /usr/bin/env sh .sqa/script.cranky-platinum-horse.sh
        container: qc.doc_cloudy-cyan-gorilla
      github.com/scipion-em/docs restructuredtext-lint:
        commands:
        - /usr/bin/env sh .sqa/script.seedy-asparagus-chameleon.sh
        container: qc.doc_sunny-corn-chinook
  QC.Lic:
    repos:
      github.com/Ratolon/scipion-docker licensee:
        commands:
        - /usr/bin/env sh .sqa/script.cranky-cyan-dodo.sh
        container: qc.lic_woozy-teal-bird
  QC.Sty:
    repos:
      github.com/Ratolon/scipion-docker hadolint:
        commands:
        - /usr/bin/env sh .sqa/script.baggy-xanthic-mouse.sh
        container: qc.sty_chummy-puce-panda
  QC.Ver:
    repos:
      github.com/Ratolon/scipion-docker get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.cheeky-magnolia-reindeer.sh
        container: qc.ver_nerdy-pear-fly
timeout: 1800
