config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/1.7.4
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/Ratolon/docs:
      branch: ibergrid22
      repo: https://github.com/Ratolon/docs
    github.com/Ratolon/scipion-docker:
      branch: ibergrid22
      repo: https://github.com/Ratolon/scipion-docker
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/Ratolon/scipion-docker git:
        commands:
        - /usr/bin/env sh .sqa/script.jumpy-platinum-peccary.sh
        container: qc.acc_leaky-bronze-goat
  QC.Doc:
    repos:
      github.com/Ratolon/docs find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.muggy-cerise-newfoundland.sh
        container: qc.doc_craggy-red-sponge
      github.com/Ratolon/docs git:
        commands:
        - /usr/bin/env sh .sqa/script.sloppy-amethyst-llama.sh
        container: qc.doc_stinky-wisteria-hare
      github.com/Ratolon/docs markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.cranky-smalt-hornet.sh
        container: qc.doc_baggy-purple-barnacle
      github.com/Ratolon/docs restructuredtext-lint:
        commands:
        - /usr/bin/env sh .sqa/script.wimpy-buff-binturong.sh
        container: qc.doc_whiny-russet-dalmatian
  QC.Lic:
    repos:
      github.com/Ratolon/scipion-docker licensee:
        commands:
        - /usr/bin/env sh .sqa/script.squeaky-olive-russel.sh
        container: qc.lic_silly-cardinal-husky
  QC.Met:
    repos:
      github.com/Ratolon/scipion-docker cff-converter-python:
        commands:
        - /usr/bin/env sh .sqa/script.scanty-cinnabar-tortoise.sh
        container: qc.met_stealthy-goldenrod-dhole
  QC.Sty:
    repos:
      github.com/Ratolon/scipion-docker hadolint:
        commands:
        - /usr/bin/env sh .sqa/script.muggy-turquoise-millipede.sh
        container: qc.sty_shaggy-orchid-ostrich
  QC.Ver:
    repos:
      github.com/Ratolon/scipion-docker get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.sleepy-razzmatazz-gecko.sh
        container: qc.ver_lovely-sapphire-harrier
timeout: 1800
