config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/1.7.4
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/Ratolon/docs:
      branch: ibergrid22
      repo: https://github.com/Ratolon/docs
    github.com/Ratolon/scipion-docker:
      branch: ibergrid22
      repo: https://github.com/Ratolon/scipion-docker
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/Ratolon/scipion-docker git:
        commands:
        - /usr/bin/env sh .sqa/script.pasty-lavender-starfish.sh
        container: qc.acc_frumpy-copper-tiger
  QC.Doc:
    repos:
      github.com/Ratolon/docs find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.geeky-aquamarine-chamois.sh
        container: qc.doc_breezy-cream-chimpanzee
      github.com/Ratolon/docs git:
        commands:
        - /usr/bin/env sh .sqa/script.queasy-white-moorhen.sh
        container: qc.doc_zippy-gold-indri
      github.com/Ratolon/docs markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.crabby-khaki-crane.sh
        container: qc.doc_trippy-champagne-squid
      github.com/Ratolon/docs restructuredtext-lint:
        commands:
        - /usr/bin/env sh .sqa/script.shabby-pink-ocelot.sh
        container: qc.doc_frumpy-mustard-cassowary
  QC.Lic:
    repos:
      github.com/Ratolon/scipion-docker licensee:
        commands:
        - /usr/bin/env sh .sqa/script.bumpy-zucchini-argentino.sh
        container: qc.lic_fuzzy-emerald-bulldog
  QC.Sty:
    repos:
      github.com/Ratolon/scipion-docker hadolint:
        commands:
        - /usr/bin/env sh .sqa/script.sickly-pumpkin-fly.sh
        container: qc.sty_flimsy-purple-tarantula
  QC.Ver:
    repos:
      github.com/Ratolon/scipion-docker get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.beady-corn-dugong.sh
        container: qc.ver_boozy-peach-cow
timeout: 1800
