config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/1.7.4
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/I2PC/scipion-docker:
      branch: afteribergrid
      repo: https://github.com/I2PC/scipion-docker
    github.com/scipion-em/docs:
      branch: release-3.0.0
      repo: https://github.com/scipion-em/docs
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/I2PC/scipion-docker git:
        commands:
        - /usr/bin/env sh .sqa/script.craggy-cobalt-capuchin.sh
        container: qc.acc_gamy-malachite-crab
  QC.Doc:
    repos:
      github.com/scipion-em/docs find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.pasty-apricot-neanderthal.sh
        container: qc.doc_gamy-aquamarine-pinscher
      github.com/scipion-em/docs git:
        commands:
        - /usr/bin/env sh .sqa/script.paltry-eggplant-maltese.sh
        container: qc.doc_surly-cerise-starfish
      github.com/scipion-em/docs restructuredtext-lint:
        commands:
        - /usr/bin/env sh .sqa/script.craggy-gamboge-uakari.sh
        container: qc.doc_flabby-dandelion-setter
  QC.Lic:
    repos:
      github.com/I2PC/scipion-docker licensee:
        commands:
        - /usr/bin/env sh .sqa/script.woozy-silver-moth.sh
        container: qc.lic_snazzy-smalt-bulldog
  QC.Sty:
    repos:
      github.com/I2PC/scipion-docker hadolint:
        commands:
        - /usr/bin/env sh .sqa/script.slaphappy-scarlet-cuttlefish.sh
        container: qc.sty_crappy-lemon-wrasse
  QC.Ver:
    repos:
      github.com/I2PC/scipion-docker get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.skanky-russet-lemur.sh
        container: qc.ver_dorky-flax-kiwi
timeout: 1800
