config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/1.7.4
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/Ratolon/docs:
      branch: ibergrid22
      repo: https://github.com/Ratolon/docs
    github.com/Ratolon/scipion-docker:
      branch: ibergrid22
      repo: https://github.com/Ratolon/scipion-docker
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/Ratolon/scipion-docker git:
        commands:
        - /usr/bin/env sh .sqa/script.sickly-flax-cuscus.sh
        container: qc.acc_woolly-white-hummingbird
  QC.Doc:
    repos:
      github.com/Ratolon/docs find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.sunny-beige-whale.sh
        container: qc.doc_pretty-khaki-insect
      github.com/Ratolon/docs git:
        commands:
        - /usr/bin/env sh .sqa/script.randy-rust-ray.sh
        container: qc.doc_crabby-buff-robin
      github.com/Ratolon/docs markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.woolly-yellow-lobster.sh
        container: qc.doc_bluesy-malachite-bandicoot
      github.com/Ratolon/docs restructuredtext-lint:
        commands:
        - /usr/bin/env sh .sqa/script.zippy-khaki-ostrich.sh
        container: qc.doc_jumpy-carmine-discus
  QC.Lic:
    repos:
      github.com/Ratolon/scipion-docker licensee:
        commands:
        - /usr/bin/env sh .sqa/script.freaky-razzmatazz-tiger.sh
        container: qc.lic_trippy-magnolia-bongo
  QC.Sty:
    repos:
      github.com/Ratolon/scipion-docker hadolint:
        commands:
        - /usr/bin/env sh .sqa/script.lovely-violet-moth.sh
        container: qc.sty_messy-cornflower-fousek
  QC.Ver:
    repos:
      github.com/Ratolon/scipion-docker get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.slaphappy-linen-baboon.sh
        container: qc.ver_boozy-lilac-mayfly
timeout: 1800
